apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-foyer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-foyer
  template:
    metadata:
      labels:
        app: tp-foyer
    spec:
      containers:
        - name: tp-foyer-container
          image: yacine0/tp-foyer-5.0.0  # Docker image
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-service
spec:
  type: NodePort
  selector:
    app: tp-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089