apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-foyer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-foyer
  template:
    metadata:
      labels:
        app: tp-foyer
    spec:
      containers:
        - name: tp-foyer-container
          image: yacine0/tp-foyer-5.0.0  # Docker image
          ports:
            - containerPort: 8089
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-service:3306/db?createDatabaseIfNotExist=true
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: ""  # Use a Kubernetes Secret for production
---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-service
spec:
  type: NodePort
  selector:
    app: tp-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089



---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-service
spec:
  type: NodePort
  selector:
    app: tp-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mysql-deployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: mysql
        template:
          metadata:
            labels:
              app: mysql
          spec:
            containers:
              - name: mysql-container
                image: mysql:5.7
                env:
                  - name: MYSQL_ALLOW_EMPTY_PASSWORD
                    value: "yacine"
                  - name: MYSQL_DATABASE
                    value: db
                ports:
                  - containerPort: 3306

---
      apiVersion: v1
      kind: Service
      metadata:
        name: mysql-service
      spec:
        type: ClusterIP
        ports:
          - port: 3306
        selector:
          app: mysql
