version: '3.8'

services:
  tp-foyer:
    build:
      context: .  # Spécifie le répertoire où se trouve votre Dockerfile
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/db?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=  # Pas de mot de passe pour root
    ports:
      - "8085:8085"  # Expose le port 8089
    depends_on:
      - docker-mysql  # Assure que MySQL démarre avant cette application
    restart: always  # Redémarre le conteneur automatiquement en cas de besoin

  docker-mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Permet un mot de passe root vide
      - MYSQL_ROOT_PASSWORD=  # Pas de mot de passe pour root
      - MYSQL_DATABASE=db  # Crée la base de données 'rahmaf'
    ports:
      - "3307:3306"  # Mappe le port 3307 du système hôte au port 3306 du conteneur
    volumes:
      - mysql-data:/var/lib/mysql  # Garde les données MySQL même après l'arrêt du conteneur

volumes:
  mysql-data:
