version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  devops:
    depends_on:
      - mysqldb
    image: rahmafarhat9/devops:1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
      "spring.datasource.username": "root",
      "spring.datasource.password": null,
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db: