version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rahmafarhat9/devops:1.0.0
    container_name: java_app
    ports:
      - "8089:8089"  # Adaptez ce port selon votre application
    depends_on:
      - database
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/db  # Exemple si vous utilisez Spring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    command: ["java", "-jar", "/app/Devops-Integration.jar"]  # Adaptez le chemin du fichier JAR
    volumes:
      - ./target:/app/target  # Vérifiez que le chemin correspond à votre structure de projet

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
