version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rahmafarhat9/devops:1.0.0
    container_name: java_app
    ports:
      - "8089:8089"  # Port de l'application
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    volumes:
      - ./target:/app/target  # Montée du répertoire target

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
